apiVersion: v1
kind: Pod
metadata:
  name: encoder
  labels:
    name: encoder
    version: stable
  annotations:
    gke-gcsfuse/volumes: "true"
    autopilot.gke.io/host-port-assignment: '{"min":5000,"max":6000}'
spec:
  restartPolicy: Always
  serviceAccountName: ksa-encoder
  terminationGracePeriodSeconds: 60
  containers:
  - image: ${LOCATION}-docker.pkg.dev/${PROJECT_ID}/${REPO}/encoder:v0.1
    name: encoder
    imagePullPolicy: Always
    ports:
    - name: udp
      containerPort: 5000
      protocol: UDP
      hostPort: 5001
    env:
    - name: ENV
      value: dev
    - name: OUTPUT_BUCKET
      value: ${GCS_OUT_NAME}
    - name: RESOLUTION
      value: "1080"
    - name: OUTPATH
      value: "/output"
    - name: FILENAME
      value: "outfile_%06d.mp4"
    volumeMounts:
    - name: gcs-fuse-csi-output
      mountPath: "/output"
  volumes:
  - name: gcs-fuse-csi-output
    csi:
      driver: gcsfuse.csi.storage.gke.io
      volumeAttributes:
        bucketName: ${GCS_OUT_NAME}
        mountOptions: "implicit-dirs"
